theme: minimal
# Name of your site (displayed in the header)
name: QuentinJcb Blog

# Short bio or description (displayed in the header)
description: Machine Learning & Quantitative Finance

markdown: kramdown
