theme: jekyll-theme-minimal
# Name of your site (displayed in the header)
name: Your Name

# Short bio or description (displayed in the header)
description: Machine learning, quantitative finance, operations research
